config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: "public/users/sessions",
      registrations: "public/users/registrations"
  }
  scope module: :public do
    resources :users do
      post "/follow", to: "users#follow", as: :follow
      delete "/unfollow", to: "users#unfollow", as: :unfollow
      get "/followers", to: "users#followers", as: :followers
      get "/followings", to: "users#followings", as: :followings
      resources :rooms, only: [:create, :show, :index] do
        resources :messages, only: [:create]
      end
    end
    resources :songs do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      collection do
        post "/search", to: "songs#search", as: :search
     #   get "search/:keyword", to: "songs#result", as: :result
        get "/tagged/:tag", to: "songs#tagged", as: :tagged
      end
    end
  end

  root "home#home"
  get '/about', to: "home#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :song
  
  validates :url, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :song
  
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/key.rb
class Key < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: :User
  belongs_to :following, class_name: :User
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :keys, dependent: :destroy
  has_many :users, through: :keys
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many :addresses, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  acts_as_taggable_on :tags
  
  mount_uploader :avatar, AvatarUploader
  
  validates :name, presence: true
  validates :description, length: { maximum: 500 }
  
  scope :by_name, ->(keyword){ where("name LIKE ?", "#{ keyword }%") }
  
  def favorited_by?(user)
    self.favorites.find_by(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  #validates :name, length: { in: 2..20 }
  
  has_many :passive_relationships, foreign_key: :followed_id, class_name: :Relationship
  has_many :active_relationships, foreign_key: :following_id, class_name: :Relationship
  has_many :followers, through: :passive_relationships, source: :following
  has_many :followings, through: :active_relationships, source: :followed
  has_many :messages, dependent: :destroy
  has_many :keys, dependent: :destroy
  has_many :rooms, through: :keys
  has_many :songs, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  mount_uploader :avatar, AvatarUploader
  
  def follow(user)
    self.active_relationships.create(followed: user)
  end
  
  def unfollow(user)
    r = self.active_relationships.find_by(followed: user)
    r.destroy
  end
  
  def following?(user)
    self.active_relationships.find_by(followed: user)
  end
  
  def has_room?(user)
    self.rooms.each do |room|
      if room.users == [self, user] || [user, self]
        return room
      end
    end
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def counter(noun, count)
    if noun == 0
      "No #{ noun }"
    else
      "#{ count } #{ noun.pluralize(count) }" 
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="col-sm-10">
  <h2 class="about-heading">利用方法</h2>
  <p class="about-text">
    1. 自分の音楽を登録
    2. プレイリストをカスタマイズ
    3. Let's enjoy music!
  </p>
</div>

app/views/home/home.html.erb
<div class="col-sm-12 relative">
  <%= render "layouts/sidebar" %>
  <div class="main-content">
    <%= render "layouts/jumbotron" %>
    
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <section class="home-content-text text-center">
          <h3>一音一会、音楽は人生に彩を与える</h4>
          <p>
            嬉しいとき、楽しいとき、悲しいとき、辛いとき、<br>
            様々な感情に出会ったときに、自分で言葉が出てこない時に、<br>
            きっと音楽は貴方の声となり、心となり、意志となります。<br>
            そんな音楽との出会いは、まさに一期一会です。<br>
            貴方との出会いを、心を、他の人とシェアしませんか。
          </p>
        </section>
        <div class="home-tags">
          <ul style="list-style-type: none;">
            <% tags = ActsAsTaggableOn::Tag.most_used(5) %>
            <% tags.each do |tag| %>
              <li><%= link_to tag.name, tagged_songs_path(tag.name) %></li>
            <% end %>
          </ul>
        </div>
        <div class="home-search">
          <%= form_tag(search_songs_path) do %>
            <%= label_tag :keyword %>
            <%= text_field_tag :keyword %>
            <%= submit_tag "Search" %>
          <% end %>
        </div>
        <div class="home-songs">
          <p>SONG SONG SONG</p>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<% if resource.errors.any? %>
  <div class="error-explanation">
    <h2><%= resource.errors.count %>件のエラーが発生しました。</h2>
    <ul class="error-list">
      <% resource.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_jumbotron.html.erb
    <section class="jumbotron">
      <h2 class="home-heading">Cheer Music</h2>
      <p>Music for you whenever</p>
    </section>

app/views/layouts/_sidebar.html.erb
<nav class="absolute sidebar text-center">
  <h2>MENU</h2>
  <% if user_signed_in? %>
    <%= form_tag(search_songs_path) do %>
      <%= label_tag :keyword %>
      <%= text_field_tag :keyword %>
      <%= submit_tag "SEARCH" %>
    <% end %>  
    <div class="own-info text-center" style="background-color: rgba(15, 195, 250, 0.4)">
      <span>
        <% if current_user.avatar.url != nil %>
          <%= image_tag(current_user.avatar.url, size: "50x50") %>
        <% end %>
      </span>
       <ul class="own-info-list">
         <li class="own-info-list-item"><%= current_user.name %></li>
         <li class="own-info-list-item"><%= link_to "MY PAGE", user_path(current_user) %></li>
         <li class="own-info-list-item"><%= link_to "EDIT", edit_user_path(current_user) %></li>
         <li class="own-info-list-item"><%= link_to "Chats", user_rooms_path(current_user) %></li>
       </ul>
    </div>
  <% end %>
  <ul class="nav-list">
    <% if user_signed_in? %>
      <li class="nav-list-item"><%= link_to "USERS", users_path %></li>
      <li class="nav-list-item"><%= link_to "SONGS", songs_path %></li>
      <li class="nav-list-item"><%= link_to "New Song", new_song_path %></li>
      <li class="nav-list-item"><%= link_to "LOGOUT", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></li>
    <% else %>
      <li class="nav-list-item"><%= link_to "HOME", root_path %></li>
      <li class="nav-list-item"><%= link_to "ABOUT", about_path %></li>
      <li class="nav-list-item"><%= link_to "LOGIN", new_user_session_path %></li>
      <li class="nav-list-item"><%= link_to "REGISTER", new_user_registration_path %></li>
    <% end %>    
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cheersong</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row" style="height: inherit;">
        <% if notice.present? %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert.present? %>
          <p class="alert"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
  
</html>